src/api/core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from core import settings
from django.conf.urls.static import static

# Deprecated in favor of DRF ::: Migration to DRF in progress
urlpatterns = [
    path("admin/", admin.site.urls),
    path("identity/", include("identity.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("", include("home.urls")),

    # api specific ::: 
    path("api/v1/event/", include("event.urls")),
]

urlpatterns += [
    path("api/v1/identity/", include("identity.api_urls")),
    path("api/v1/platform/", include("home.api_urls")),
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/api/dashboard/urls.py
from django.urls import path
from .views import (
    ProfileUpdateView,
    PasswordUpdateView,
    ScheduleManagerView,
    DashboardView,
    EventListView,
    EventDeleteView,
    EventListBusinessHoursView,
    EventDeleteBusinessHoursView,
    LogoutView,
)
# @depreciated: migrating urls to DRF api
urlpatterns = [
    path("profile-update", ProfileUpdateView.as_view(), name="profile-update"),
    path("password-update", PasswordUpdateView.as_view(), name="password-update"),
    path("logout", LogoutView.as_view(), name="logout"),

    # TODO :::
    path("", DashboardView.as_view(), name="dashboard"),
    path("manage/schedule", ScheduleManagerView.as_view(), name="schedule-manager"),
    path("events", EventListView.as_view(), name="events"),
    path("events/detach", EventDeleteView.as_view(), name="event-delete"),
    path(
        "events/business-hours",
        EventListBusinessHoursView.as_view(),
        name="business-hours",
    ),
    path(
        "events/business-hours/detach",
        EventDeleteBusinessHoursView.as_view(),
        name="delete-business-hours",
    ),
]

src/api/dashboard/models/user.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, BaseUserManager
from django.utils.translation import gettext_lazy as _
from dashboard.enums import EventTypes


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


def rename_file(instance, filename):
    directory = "profile_photos/"
    file_ext = filename.split(".")[-1]
    file_name = f"profile_photo_{instance.id}.{file_ext}"

    return directory + file_name


# Create your models here.
class User(AbstractUser):
    username = None
    first_name = None
    last_name = None

    objects: BaseUserManager = CustomUserManager()

    email = models.EmailField("email_address", unique=True)
    name = models.CharField("name", max_length=190, blank=True)
    company = models.CharField("company", max_length=190, blank=True)
    position = models.CharField("position", max_length=190, blank=True)
    profile_summary = models.TextField("profile_summary", blank=True)
    profile_photo = models.ImageField(
        name="profile_photo",
        upload_to="dashboard.models.user.rename_file",
        blank=True,
        null=True,
        width_field="width_field",
        height_field="height_field",
    )
    public_id = models.CharField("public_id", max_length=190, blank=True, unique=True)

    height_field = models.IntegerField(default=180, null=True, blank=True)
    width_field = models.IntegerField(default=180, null=True, blank=True)
    email_verified = models.BooleanField(default=False, blank=False, null=False)
    email_verified_at = models.DateTimeField(blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return str(self.email)

    def save(self, *args, **kwargs):
        if self.public_id == "" or self.public_id is None:
            id_exists = True
            while id_exists:
                p_id = uuid.uuid4().hex[:7]
                if not User.objects.filter(public_id=p_id).exists():
                    id_exists = False
            self.public_id = p_id

        super().save(*args, **kwargs)

src/api/dashboard/forms/password_update_form.py
from django.contrib.auth.forms import PasswordChangeForm
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash


class PasswordUpdateForm(PasswordChangeForm):

    class Meta:
        model = get_user_model()
        fields = []

    def __init__(self, *args, request=None, user=None, **kwargs):
        self.request = request
        self.user = user

        super().__init__(user=self.user, *args, **kwargs)

        self.fields["old_password"].widget = forms.PasswordInput(
            attrs={"placeholder": "Existing Password"}
        )
        self.fields["new_password1"].widget = forms.PasswordInput(
            attrs={"placeholder": "New Password"}
        )
        self.fields["new_password2"].widget = forms.PasswordInput(
            attrs={"placeholder": "Confirm New Password"}
        )

        self.fields["old_password"].label = "Current Password"
        self.fields["new_password1"].label = "Choose a new password"
        self.fields["new_password2"].label = "Confirm your new password"

    def clean_password2(self):
        password2 = self.cleaned_data.get("new_password2", None)
        if password2 != self.cleaned_data.get("new_password1"):
            raise forms.ValidationError("Password 1 and 2 does not match")

        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data["new_password1"])

        if commit:
            self.user.save()
            update_session_auth_hash(self.request, self.user)

        return self.user

src/api/dashboard/views/dashboard_view.py
from dashboard.models import Event
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import FormView
from core.services.event_service import EventService
from dashboard.enums import EventTypes
from dashboard.forms import ScheduleManagerForm
from typing import Any
from datetime import datetime
from django.contrib import messages
from django.shortcuts import redirect
from dashboard.models.user import User


class DashboardView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    form_class = ScheduleManagerForm
    succeess_url = reverse_lazy("dashboard")
    success_message = "Your schedule has been updated!"
    template_name = "dashboard/index.html"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        """Include some extra data, before passing it over to the template"""
        context = super().get_context_data(**kwargs)

        context["choices"] = EventTypes.options()
        context["weekday_num"] = datetime.now().isoweekday()
        context["business_hours"] = EventService.get_business_hours(
            user=self.request.user
        )
        context["display_name"] = getattr(self.request.user, "name", "")
        context["position"] = getattr(self.request.user, "position", "")

        appointments = Event.objects.filter(
            start_date__gte=datetime.now().date(),
            type=EventTypes.PUBLIC.value,
        ).order_by("start_date", "start_time")[:7]
        upcoming_appointments = EventService.prep_event_data(
            appointments, format_date_time=True
        )

        context["upcoming_appointments"] = upcoming_appointments
        context["next_appointment"] = (
            upcoming_appointments.pop(0) if len(upcoming_appointments) > 0 else {}
        )

        return context

    def form_valid(self, form):
        type_input_value = (
            str(form.cleaned_data["type"])
            if "type" in form.cleaned_data
            else EventTypes.BUSINESS_HOURS.value
        )
        user_timezone = EventService.extract_user_timezone(form.data)

        start_date = form.cleaned_data["start_date"]
        start_time = EventService.convert_to_utc(
            date_str=str(start_date),
            time_str=str(form.cleaned_data["start_time"]),
            user_timezone=user_timezone,
        )

        end_date = form.cleaned_data["end_date"]
        end_time = EventService().convert_to_utc(
            date_str=str(end_date),
            time_str=str(form.cleaned_data["end_time"]),
            user_timezone=user_timezone,
        )

        frequency = EventService.get_frequency(form.cleaned_data["frequency"])

        if start_time == None or end_time == None:
            messages.error(
                self.request,
                "Start time/End time could not be processed. Please ensure the correct slots were selected",
            )
            return self.form_invalid(form)

        if frequency == "" and (start_date == end_date and start_time > end_time):
            messages.error(
                self.request,
                "Start time cannot be greater than End time, when start date and end date are the same",
            )
            return self.form_invalid(form)

        title = EventService.get_event_title(type_input_value)
        event = Event(
            frequency=EventService().get_frequency(form.cleaned_data["frequency"]),
            user=self.request.user,
            title=title,
            type=type_input_value,
            start_date=start_date,
            start_time=start_time,
            end_date=end_date,
            end_time=end_time,
            timezone=user_timezone,
        )

        event.save()
        messages.success(self.request, "Your schedule has been updated!")
        return redirect("schedule-manager")

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return super().form_invalid(form)

src/api/dashboard/views/event_delete_business_hours_view.py
from django.http import JsonResponse
from django.views.generic import DeleteView
import json
from dashboard.models import Event
from dashboard.enums import EventTypes
from django.contrib.auth.mixins import LoginRequiredMixin


class EventDeleteBusinessHoursView(LoginRequiredMixin, DeleteView):
    def delete(self, request, *args, **kwargs):
        body = request.body.decode("utf-8")
        if "id" in body:
            data = json.loads(body)

        event = Event.objects.filter(
            user=request.user, id=data["id"], type=EventTypes.BUSINESS_HOURS.value
        ).first()

        if event:
            event.delete()
            return JsonResponse(data=[{"status": True}], safe=False)

        return JsonResponse(
            data=[{"status": True, "error": "Event not found or not deleted"}],
            status=400,
            safe=False,
        )

src/api/dashboard/views/event_delete_view.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
import json
from dashboard.models import Event
from django.http import JsonResponse


class EventDeleteView(LoginRequiredMixin, View):
    def delete(self, request):
        body = request.body.decode("utf-8")
        if "id" in body:
            data = json.loads(body)
            event = Event.objects.filter(user=request.user, id=data["id"]).first()
            if event:
                event.delete()

            return JsonResponse(
                data=[{"status": True}],
                safe=False,
            )

        return JsonResponse(
            data=[{"status": False, "message": "Invalid ID or event not found"}],
            status=400,
        )

src/api/dashboard/views/event_list_business_hours_view.py
from django.views import View
from core.services import EventService
from django.http import JsonResponse
from typing import List, Dict
from django.contrib.auth.mixins import LoginRequiredMixin


class EventListBusinessHoursView(LoginRequiredMixin, View):
    def get(self, request):
        data: List[Dict] = EventService.get_business_hours(request.user)

        return JsonResponse(
            data=data,
            safe=False,
        )

src/api/dashboard/views/event_list_view.py
from django.views import View
from django.http import JsonResponse
from core.services import EventService
from django.contrib.auth.mixins import LoginRequiredMixin


class EventListView(LoginRequiredMixin, View):
    def get(self, request):
        return JsonResponse(
            EventService.get_events(request.GET, request.user.public_id), safe=False
        )

src/api/dashboard/views/logout_view.py
from django.views import View
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin


class LogoutView(LoginRequiredMixin, View):
    def post(self, request):
        logout(request)
        messages.success(request, "Goodbye! See you soon")
        return redirect("index")

src/api/dashboard/views/password_update_view.py
from typing import Union
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import UpdateView
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from core.utils import get_template_path
from dashboard.forms import PasswordUpdateForm
from dashboard.models.user import User
from dashboard.tasks import email_sender
from django.contrib.auth.models import AbstractBaseUser, AnonymousUser


class PasswordUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Handles User password updating
    """

    form_class = PasswordUpdateForm
    template_name = "dashboard/password_update.html"
    success_message = "Password update was successful!"
    success_url = reverse_lazy("password-update")

    def get_object(self):
        return self.request.user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        # Necessary because great-grand base class, forms.Form, does not take instance as an argument
        kwargs.pop("instance")

        kwargs["request"] = self.request
        kwargs["user"] = self.request.user

        return kwargs

    def form_valid(self, form: PasswordUpdateForm):
        form.save()
        template = get_template_path("identity", "emails/password_updated.email.html")

        email_sender.delay("Password Updated!", [self.request.user.email], template, {})
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, f"{form.errors}")
        return super().form_invalid(form)

src/api/dashboard/views/profile_update_view.py
from typing import Any
from dashboard.forms import ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin


class ProfileUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = ProfileUpdateForm
    template_name = "dashboard/profile_update.html"
    success_message = "Profile updated..."

    def get_object(self):
        """
        Override the default. Inherited from
        UpdateView -> BaseUpdateView -> ModelFormMixin -> SingleObjectMixin
        """

        return self.request.user

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context["email_verified"] = self.request.user.email_verified

        return context

    def get_success_url(self):
        """
        Override the default. Inherited from
        UpdateView -> BaseUpdateView -> ModelFormMixin -> FormMixin
        """

        return reverse_lazy("profile-update")

    def form_invalid(self, form):
        """
        Override the default. Inherited from
        UpdateView -> BaseUpdateView -> ModelFormMixin -> FormMixin
        """

        messages.error(self.request, f"{form.errors}")
        return super().form_invalid(form)

src/api/dashboard/templates/dashboard/index.html
{% extends "Base/dashboard.html" %}
{% load static %}
{% block dashboard-main-content %}
 <div class="row">
    <div class="col-lg-9" >
        <div class="dashboard-height">
            <div class="dashboard-container">
                <div class="appointments-header">
                    <div class="row">
                        <div class="col-xl-8 col-lg-12 col-md-12 col-sm-12">
                                <div class="d-flex profile-dp">
                                    <div class="profile-img">
                                        {% if user.profile_photo is not None and user.profile_photo != '' %}
                                            <img src="{{ user.profile_photo.url }}" alt="Profile Photo" />
                                        {% else %}                                        
                                            <img src="http://placehold.it/180" alt="Profile Photo" />
                                        {% endif %}
                                    </div>
                                    <div class="profile-header-section text-start p-md-4">
                                        <h1 class="text-theme fw-bold">{{ user.name }}</h1>
                                        <h6 class="mb-5">
                                            {% if user.position is not None %}
                                                {{ user.position }},
                                            {% endif %}
                                            {{ user.company }}
                                        </h6>
                                    </div>
                                </div>
                        </div>
                        <div class="col-xl-4 col-lg-12 col-md-12 col-sm-12 next-appointent">
                                {% if next_appointment %}
                                    <div class="d-flex flex-row-reverse">
                                        <div class="px-3 next-appointent-time">
                                            <h1 class="text-theme"> {{ next_appointment.start_time }} </h1>
                                        </div>
                                        <div class="next-appointent-date">
                                            <h6 class="card-title text-left text-green"> <i class="fa fa-clock px-1 text-theme"></i> {{ next_appointment.start }} </h6>
                                            <div class="meetings text-center">
                                                <span>Next Meeting</span>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card metton-calendar-card">
                    <div class="card-body appointments">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="javascript:void(0)" role="tab" aria-controls="home" aria-selected="true">Schedule</a>
                            </li>
                        </ul>
                        <div id='manage-schedules'></div>
                    </div>
                    <div class="unsupported-device">
                        <span><i class="fa fa-bell-slash"></i> Unsupported Device </span> 
                        <div>Your calendar is best managed on a desktop device. Please switch to a larger screen to view your calendar.</div>
                        <p class="alert alert-success mt-3"> A version compatible with your device is coming soon! </p>
                    </div>
                </div>
                <div class="modal" tabindex="-1" id="appointment-modal"> 
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Event Details</h5>
                                <span aria-hidden="true" class="close-calendar-modal" data-bs-dismiss="modal" aria-label="Close">
                                            <i class="fa fa-times-circle text-danger"></i>
                                        </span>
                            </div>
                            <div class="modal-body pl-3 pr-3">
                                <div class="row">
                                    <div class="mb-2 pl-3 pr-3">
                                        <table class="table table-striped table-bordered ">
                                            <tr class="pt-5">
                                                <td>Title</td>
                                                <td><b  id="eventTitle"></b></td>
                                            </tr>
                                            <tr class="pt-5">
                                                <td>Start Date</td>
                                                <td id="eventStart"></td>
                                            </tr>
                                            <tr class="pt-5">
                                                <td>End Date</td>
                                                <td id="eventEnd"></td>
                                            </tr>
                                            <tr class="pt-5">
                                                <td>Frequency</td>
                                                <td id="eventFreq"></td>
                                            </tr>
                                        </table>
                                    </div>
                                    <hr/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <div class="col-lg-3 col-md-12 col-sm-12">
        <div class="sidebar-content shadow-lg">
            <div class="sidebar-header">
                <h4 class="card-title text-left text-theme"> <i class="fa fa-calendar-days text-green mx-2"></i> Upcoming </h4>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="meetings">
                        {% if upcoming_appointments  %}
                            {% for appointment in upcoming_appointments %}
                                <div>
                                    <h6> <i class="fa fa-briefcase"></i> {{ appointment.title  }}</h6>
                                    <p> <i class="fa fa-clock text-success"></i> {{ appointment.start }} : {{ appointment.start_time }}
                                    </p>
                                    <p> <i class="fa fa-clock text-danger"></i> {{ appointment.end }} : {{ appointment.end_time }}
                                    </p>
                                    
                                    <p>
                                    {% if appointment.timetable %}
                                        <span>Repeated</span> {{  appointment.timetable }}
                                    {% else %}
                                        No repeat
                                    {% endif %}
                                    </p>


                                    {% if forloop.counter != upcoming_appointments|length %}
                                        <hr class="clearfix"/>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        {% else %}
                            <p><i class="fa fa-briefcase-clock text-danger"></i> Nothing here yet  </p>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer_script %}
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js'></script>
<script src="{% static 'js/appointment.js' %}"></script>
{% endblock %}

src/api/dashboard/templates/dashboard/profile_update.html
{% extends "Base/dashboard.html" %} {% block dashboard-main-content %}
{% load widget_tweaks %}
<div class="row min-vh-100">
  <div class="col-lg-12">
    <div class="container">
      <div class="dashboard-container">
        <div class="card text-center">
          <div class="card-header">
            <h3 class="card-title">Update Profile</h3>
          </div>
          {% if not email_verified %}
          <div class="alert alert-warning">
            <strong><i class="fa fa-warning"> </i></strong> Your email is not verified.  
            Please click 
            <form class="d-inline" action="{% url 'resend-email-verification' %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="HERE" class="btn btn-outline-secondary-subtle p-0" />
            </form> to verify. 
            <br/>You'll receive an email with verification instructions.
          </div>
          {% endif %}
          <div class="card-body text-left">
            <form
              method="POST"
              action="{% url 'profile-update' %}"
              enctype="multipart/form-data"
            >
              {% csrf_token %}
              <div class="row">
                <div class="col-md-5">
                  <div class="form-group">
                    <div class="col-md-10">
                      <div
                        class="profile-photo-preview mb-3"
                        id="profile-photo-preview"
                      >
                        {% if user.profile_photo is not None and user.profile_photo != '' %}
                        <img
                          src="{{ user.profile_photo.url }}"
                          alt="Profile Photo"
                          id="profile-photo-preview-img"
                        />
                        {% else %}
                        <img
                          src="http://placehold.it/180"
                          alt="Profile Photo"
                          id="profile-photo-preview-img"
                        />
                        {% endif %}
                      </div>

                      <input
                        type="file"
                        class="form-control"
                        name="profile_photo"
                        id="id_profile_photo"
                        accept="image/*"
                        onchange="previewProfilePhoto(this);"
                      />

                      {% if user.public_id %}
                      <div class="card mt-5 meeting-link">
                        <div
                          class="card-header text-lg-start d-flex justify-content-between"
                        >
                          <h6 class="card-title">Booking link</h6>
                          <span
                            class="invisible text-success"
                            id="clipboardAlert"
                            ><i class="fa fa-check-circle"></i> copied</span
                          >
                        </div>
                        <div class="card-body">
                          <div class="form-row">
                            <div class="col-auto">
                              <div class="input-group">
                                <input
                                  type="text"
                                  class="form-control"
                                  readonly
                                  value="{{ request.scheme }}://{{ request.get_host }}{% url 'meet' user.public_id %}"
                                  id="copyText"
                                />
                                <div class="input-group-append">
                                  <div class="input-group-text" id="clicky">
                                    <i class="fa fa-copy p-2"></i>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="col-md-7">
                  {% for field in form %} {% if field.name != 'profile_photo' %}
                  <div class="form-group row mb-3">
                    <label
                      for="{{ field.auto_id }}"
                      class="col-sm-5 col-form-label"
                      >{{ field.label }}</label
                    >
                    <div class="col-sm-7">{{ field|add_class:"form-control" }}</div>
                  </div>
                  {% endif %} {% endfor %}
                </div>
                <div class="col-md-12">
                  <div class="form-group m-auto">
                    <button type="submit" class="btn btn-theme btn-block">
                      Update
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}